---
# tasks file for backup

- name: install common soft
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - gnupg2

- name: if pip version
  block:
    - name: install pip upgrade
      ansible.builtin.pip:
        name: pip
        executable: "{{ duplicitybkp_pip_path }}"
        state: latest
    - name: install pip tools
      ansible.builtin.pip:
        name: wheel
        executable: "{{ duplicitybkp_pip_path }}"
    - name: install duplicity pip
      ansible.builtin.pip:
        name: "{{ duplicitybkp_packages_list_pip }}"
        executable: "{{ duplicitybkp_pip_path }}"
  when:
    - duplicitybkp_bin_type == 'pip'

- name: install deb version
  block:
    - name: install soft
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - duplicity
          - python-pip

    - name: install soft for swift
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python-swiftclient
      when: "'swift' in bkptype"

    - name: install soft for s3
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python-boto3
      when:
        - "'s3' in bkptype"
  when:
    - duplicitybkp_bin_type == 'deb'

- name: create group
  group:
    name: "{{ backup_user }}"
    state: present

- name: create backups dir
  file:
    path:  "{{ item }}"
    state: directory
    owner: "root"
    group: "{{ backup_user }}"
    mode:  0770
  loop:
    - "{{ backup_dir }}"
    - "{{ backup_dir }}/{{ backup_name }}"
    - "{{ backup_dir }}/{{ backup_name }}/files"
    - "{{ backup_dir }}/{{ backup_name }}/databases"
