---
# tasks file for backup
- name: install soft
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - duplicity
      - python-pip
      - gnupg2

- name: create group
  group:
    name: "{{ backup_user }}"
    state: present

- name: create backups dir
  file:
    path:  "{{ item }}"
    state: directory
    owner: "root"
    group: "{{ backup_user }}"
    mode:  0770
  loop:
    - "{{ backup_dir }}"
    - "{{ backup_dir }}/{{ backup_name }}"
    - "{{ backup_dir }}/{{ backup_name }}/files"
    - "{{ backup_dir }}/{{ backup_name }}/databases"
