---
- name: add duplicity
  include_tasks: duplicity.yml
  when: bkptype == "duplicity" or bkptype == "swift"

- name: backup mysql
  include_tasks: mysql.yml
  when: bkptype == "mysql"

- name: backup mysql with all params in cfg
  include_tasks: mysql_fullcfg.yml
  when: bkptype == "mysql_fullcfg"
  tags: mysqlbkp_install

- name: configure client for mysql backup
  include_tasks: mysqlclient.yml
  when: bkptype == "mysqlclient"

- name: configure client for mysql backup with all params in cfg
  include_tasks: mysqlclient_fullcfg.yml
  when: bkptype == "mysqlclient_fullcfg"

- name: swift backup by duplicity
  include_tasks: swift.yml
  when: bkptype == "swift"

- name: swift backup by duplicity with prometheus metrics
  include_tasks: swift_fullcfg.yml
  when: bkptype == "swift_fullcfg"
