---
# defaults file for backup
backup_user: "backup"
backup_dir: "/home/backup"
bkpprefix: ""
mysqlbkp_user: "bkp"
mysqlbkp_pass: "{{ lookup('password', 'credentials/' + mysqlbkp_host + '/mysql_bkp_password length=14 chars=ascii_letters,digits,hexdigits') }}"
